LineLength:
  Max: 300

Layout/AlignParameters:
  Exclude:
    - '**/metadata.rb'

Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

EndOfLine:
  Enabled: false
