language: generic
sudo: false
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
script: chef exec rake travis
before_install:
- openssl aes-256-cbc -K $encrypted_92c995406a15_key -iv $encrypted_92c995406a15_iv
  -in supermarket.pem.enc -out supermarket.pem -d
deploy:
  provider: chef-supermarket
  user_id: vsts_agent_cookbook
  client_key: supermarket.pem
  cookbook_category: Others
  on:
    tags: true
